id: AE818AEBF
title: Raising the Windhorse
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:09:59.719789
  last_modified_at: 2022-03-01 00:09:59.719796
